name: CI Pipeline
on: [push, pull_request]

jobs:
  explore:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v5
      - run: ls ${{ github.workspace }}

  test:
    runs-on: ubuntu-latest
    needs: explore

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Black Check
        run: |
          black --check .
      - name: Run Flake8
        run: |
          flake8 .
      - name: Run Tests with Coverage
        run: |
          python manage.py migrate
          coverage run --source='polls' manage.py test
      - name: Generate Coverage Report
        run: |
          coverage report
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}